package org.wso2.carbon.social.adaptor;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

public class QueryAdapater implements AdapterInterface {

	@Override
	public ResultSet getPaginatedActivitySet(Connection connection,
			String targetId, String tenant, String order, int limit, int offset)
			throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public ResultSet getPopularTargetSet(Connection connection, String type,
			String tenantDomain, int limit, int offset) throws SQLException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public long insertCommentActivity(Connection connection, String json,
			String targetId, String userId, String tenantDomain,
			int totalLikes, int totalUnlikes, int timeStamp)
			throws SQLException {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public void insertRatingActivity(Connection connection,
			long autoGeneratedKey, String targetId, String userId,
			String tenantDomain, int rating, int timeStamp) throws SQLException {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void insertLikeActivity(Connection connection, String targetId,
			String actor, String tenantDomain, int likeValue, int timestamp)
			throws SQLException {
		// TODO Auto-generated method stub
		
	}

}
