package org.wso2.carbon.social.adapter;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

public interface AdapterInterface {
	
	public abstract ResultSet getPaginatedActivitySet(Connection connection,
			String targetId, String tenant, String order, int limit, int offset) throws SQLException;
	
	public abstract ResultSet getPopularTargetSet(Connection connection,
			String type, String tenantDomain, int limit, int offset)
			throws SQLException;
	
	public abstract long insertCommentActivity(Connection connection,
			String json, String targetId, String userId, String tenantDomain,
			int totalLikes, int totalUnlikes, int timeStamp)
			throws SQLException;
	
	public abstract void insertRatingActivity(Connection connection,
			long autoGeneratedKey, String targetId, String userId,
			String tenantDomain, int rating, int timeStamp) throws SQLException;
	
	public abstract void insertLikeActivity(Connection connection,
			String targetId, String actor, String tenantDomain, int likeValue,
			int timestamp) throws SQLException;

}
